[tool.black]
line-length = 88
target-version = ["py312"]
extend-exclude = '''
(
  venv/
  | \.venv/
  | sandbox/
)
'''

[tool.mypy]
plugins = ["pydantic.mypy"]
strict = false
disallow_any_explicit = false
warn_unused_ignores = true
warn_redundant_casts = true
exclude = ["venv/", "\\.venv/", "sandbox/"]

[[tool.mypy.overrides]]
module = ["airflow.*"]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["boto3.*"]
ignore_missing_imports = true

[tool.pylint.MAIN]
ignore = ["venv", "sandbox"]
ignore-patterns = ["^\\.venv$"]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "retail-footfall-pipeline"
version = "0.1.0"
description = "Retail footfall ETL pipeline"
requires-python = ">=3.12"

#setup custom for current repository

[tool.setuptools]
packages = ["etl", "src"]
